student_id <- c(101, 102, 103, 104)
student_name <- c("Asha", "Ravi", "Kiran", "Meena")
marks <- c(85, 78, 92, 88)
students <- data.frame(student_id, student_name, marks)
write.csv(students, "students.csv", row.names = FALSE)
data_read <- read.csv("students.csv")
print("Original Data:")
print(data_read)
data_read$grade <- ifelse(data_read$marks >= 90, "A",
                          ifelse(data_read$marks >= 80, "B", "C"))
print("Edited Data:")
print(data_read)
write.csv(data_read, "students_updated.csv", row.names = FALSE)
final_data <- read.csv("students_updated.csv")
print("Final Data from File:")
print(final_data)